### ISSUE TITLE
about Serenity BDD style report

### ISSUE THREAD

**Issue by roughsoft** [gkushang/codeceptjs-bdd#32]
https://serenity-js.org
I like this style report.
I like your project:codeceptjs-bdd+playwright.
are there any plan about this style report?

**Comment by gkushang** [comment]
Hi @roughsoft 

Not yet. But we are planning to build a report other than Allure. Something like this -- https://www.npmjs.com/package/cucumber-html-reporter. Pls stay tuned.

**Comment by roughsoft** [comment]
cool!
https://github.com/wswebcreation/multiple-cucumber-html-reporter
Maybe you can ref it.

**Comment by gkushang** [comment]
Migrated this repo to Salesforce Open Source Platform - https://github.com/salesforce/codeceptjs-bdd
