### ISSUE TITLE
support GitHub action

### ISSUE THREAD

**Issue by roughsoft** [gkushang/codeceptjs-bdd#34]
I use GitHub action for ci.
Is there any plan about GitHub action?
thank you!

**Comment by gkushang** [comment]
Travis-CI is enabled for this repo which runs CI tests too, but it seems to have an issue reporting status back to Github. ATM- it'd be good to explore other options as Actions or CircleCI, will take a look at it!!

TravisCI - https://travis-ci.org/github/gkushang/codeceptjs-bdd

**Comment by roughsoft** [comment]
thanks!
